version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - db:/var/lib/postgresql/data

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    restart: unless-stopped
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  sonarqube:
    image: sonarqube
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9092:9092"
volumes:
  db:
    driver: local
